### PR TITLE
Sort

### LINKED ISSUE #5: support for re-ordering imports
Add support for re-ordering imports

### PR DESCRIPTION
**Pull request by greg0ire**
Fixes #5 

This is my very first piece of vimscript, so do not hesitate to comment if you see something you do not like, I'm here to learn :)

Checklist :

- [x] handle nominal case
- [x] write some docs

A setting may be added to automatically sort the statements, but I guess that will be another PR.

Edge cases I can think of and my solution does not handle (yet) :

```php
<?php
namespace Foo;

use Baz;
use Bar; // no newline after that
class FooBar
{
}
```

```php
<?php
namespace Foo;

use Baz;

use Bar;


class FooBar
{
}
```

```php
<?php
namespace Foo;

class FooBar
{
    use MyTrait;
}
```

### CODE REVIEW

**Comment by greg0ire** [comment]
Edge cases I can think of and my solution does not handle (yet) :

```php
<?php
namespace Foo;

use Baz;
use Bar; // no newline after that
class FooBar
{
}
```

```php
<?php
namespace Foo;

use Baz;

use Bar;


class FooBar
{
}
```

```php
<?php
namespace Foo;

class FooBar
{
    use MyTrait;
}
```

**Comment by arnaud-lb** [comment]
Looks great :) Can not wait to merge :)

**Comment by greg0ire** [comment]
Thanks! I think it can be better if I can find out how to sort everything from the first use statement (easy I think) until the first blank line until the `class` keyword (excluding the blank line itself). This should take care of pretty much all the edge cases.

**Comment by greg0ire** [comment]
All in all, I think this should be merged as is. I've been using this for a week, and when you're already using vim-php-namespace, you don't fall in any of the edge cases I gave (apart from the one about traits, but why would one try to sort when there is nothing to sort?). I would say let's keep it simple, the code will be easier to understand that way. People can make PRs if there is a real need for one of these edge cases. @arnaud-lb what do you think?

**Comment by arnaud-lb** [comment]
Merged, thanks!

**Comment by greg0ire** [comment]
Yay! Enjoy the new feature :)

**Pull request merged**
